version: '3'
services:
  fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - microweber:/usr/src/microweber
    links:
      - selenium
  selenium:
    image: selenium/standalone-firefox
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - microweber:/usr/src/microweber
    links:
      - fpm
  front:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - microweber:/usr/src/microweber
    links:
      - fpm
volumes:
     microweber: